roles:
  - role: curator
     actions:
       - labels
       - close_issue
       - open_issue

  - role: maintainer
     actions:
       - close_issue
       - open_issue

users:
  - name: alexellis
    roles:
      - maintainer
  - name: rgee0
    roles:
      - maintainer
      - curator

curators:
 - viveksyngh
 
features:
 - dco_check
 - comments

contributing_url: https://github.com/alexellis/derek/blob/master/CONTRIBUTING.md
