provider:
  name: openfaas
  gateway: http://127.0.0.1:8080

functions:
  fn1:
    lang: python
    handler: ./fn1
    image: viveksyngh/fn1
    environment: {}
  fn2:
    lang: python
    handler: ./fn2
    image: viveksyngh/fn2
    environment: {}
  fn3:
    lang: python
    handler: ./fn3
    image: viveksyngh/fn3
    environment: {}
  fn4:
    lang: python
    handler: ./fn4
    image: viveksyngh/fn4
    environment: {}
  fn5:
    lang: python
    handler: ./fn5
    image: viveksyngh/fn5
    environment: {}
# fn6:
#    lang: python
#    handler: ./fn6
#    image: viveksyngh/fn6
