provider:
  name: faas
  gateway: http://127.0.0.1:8080

functions:
  fn1:
    lang: python
    handler: ./fn1
    image: viveksyngh/fn1
  fn2:
    lang: python
    handler: ./fn2
    image: viveksyngh/fn2
  fn3:
    lang: python
    handler: ./fn3
    image: viveksyngh/fn3
  fn4:
    lang: python
    handler: ./fn4
    image: viveksyngh/fn4
